# Generated by Django 4.1.6 on 2023-02-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="numberOfMovies",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="movie",
            name="numberOfActors",
            field=models.IntegerField(default=1),
        ),
    ]
